#:kivy 1.0

<ResultsLayout>:
    # manager: root.manager
    id: rlayout
    GridLayout:
        cols: 1
        # root.get_data()
        # on_kv_post:
        Button:
            text: "Test Method"
            on_press: root.gen_favorites()

    # GridLayout:
    #     cols: 5
    #     rows: 4
        # size_hint_y: None
        # on_kv_post:
        #     for target in range(root.itera): \
        #     print(target), print(target)
            
                
